services:
  local-resolver:
    container_name: local-resolver
    image: ghcr.io/0xerr0r/blocky:v0.24
    restart: unless-stopped
    ports:
      - 127.0.0.1:153:53/udp
    volumes:
      - ./blocky.yaml:/app/config.yml
      - /etc/hosts:/etc/hosts

  docker-hoster:
    container_name: docker-hoster-ir
    restart: unless-stopped
    image: docker.arvancloud.ir/dvdarias/docker-hoster
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/hosts:/tmp/hosts

  auth:
    container_name: auth-ir-theos
    depends_on:
      - dns-server
      - coap
      - docker-hoster
      - local-resolver
      - sing-box
    restart: unless-stopped
    image: ghcr.io/theos-dns/auth:latest
    network_mode: host
    environment:
      - FORWARD_TO=sing-box
      - PORTS=80,443
      - DB_PATH=/root/app/auth/db/database.sqlite3
      - UPSTREAM=${UPSTREAMS}
      - PROTECT=dns-server:53@53,dns-server:853@853,dns-server:3443@3443,coap:85@5688
      - STARTUP_SLEEP=5
      - RESOLVER=127.0.0.1:153
      - ADMIN_TOKEN=${ADMIN_TOKEN}
    volumes:
      - ${PWD}/database-auth.sqlite3:/root/app/auth/db/database.sqlite3
      - /etc/hosts:/etc/hosts
      - allowedIps:/var/nginx

  sing-box:
    container_name: sing-box-ir-theos
    restart: unless-stopped
    image: ghcr.io/sagernet/sing-box:v1.10.1
    command: run --config-directory /root/configs
    volumes:
      - ./sing-box-configs:/root/configs

  coap:
    container_name: coap-theos
    restart: unless-stopped
    image: ghcr.io/theos-dns/coap:latest
    environment:
      - LOOKUP_SERVER=dns-server:53

  dns-server:
    container_name: coredns-theos
    restart: unless-stopped
    image: ghcr.io/theos-dns/coredns:latest
    hostname: coredns
    command: -conf /home/CoreConfigFile/coredns.config
    environment:
      - IR_SERVER_IP=${IR_SERVER_IPS}
      - EU_SERVER_IP=${EU_SERVER_IPS}
      - SSL_KEY_PATH=/home/ssl-keys/key.pem
      - SSL_CERT_PATH=/home/ssl-keys/cert.pem
      - SSL_CA_PATH=/home/ssl-keys/origin_ca_rsa_root.pem
    volumes:
      - ./ssl-keys:/home/ssl-keys
      - ./coredns.config:/home/CoreConfigFile/coredns.config
      - hosts-files:/etc/hosts_dir


volumes:
  allowedIps:
  hosts-files: